# -*- coding: utf-8 -*-
"""hicode

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1JF4B0rtqSkDZmV2vUs5iK1n9p7hBT_dE
"""

# Program to respond with "Hello, World!" if the user says "hi"
user_input = input("Say something: ").strip().lower()

if user_input == "hi":
    print("Hello, World!")
else:
    print("You didn't say 'hi'!")