# -*- coding: utf-8 -*-
"""pie

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1JF4B0rtqSkDZmV2vUs5iK1n9p7hBT_dE
"""

from google.colab import files
from PIL import Image
import matplotlib.pyplot as plt

# Upload a local image file (choose your pie image)
uploaded = files.upload()  # Interactive file upload

# Open the uploaded image (use the first uploaded file)
image = Image.open(list(uploaded.keys())[0])

# Display the pie image
plt.imshow(image)
plt.axis('off')  # Hide the axes
plt.show()

