# -*- coding: utf-8 -*-
"""pie2

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1JF4B0rtqSkDZmV2vUs5iK1n9p7hBT_dE
"""

# Commented out IPython magic to ensure Python compatibility.
# # Install Streamlit and pyngrok
# !pip install streamlit
# !pip install pyngrok
# 
# # Create a Streamlit app to display a pie image
# %%writefile app.py
# import streamlit as st
# from PIL import Image
# 
# # Title of the app
# st.title("Pie Image Display")
# 
# # Display an image of a pie
# image_url = "https://upload.wikimedia.org/wikipedia/commons/4/49/Apple_pie.jpg"  # URL of the pie image
# image = Image.open(image_url)
# 
# # Show the image in the app
# st.image(image, caption='Delicious Apple Pie', use_column_width=True)